# Copied from https://github.com/Azure/azure-rest-api-specs/blob/main/.github/.prettierrc.yaml

plugins:
  - prettier-plugin-organize-imports

# Aligned with microsoft/typespec
printWidth: 100

overrides:
  # tsconfig.json is actually parsed as JSONC
  - files:
      - tsconfig.json
      - tsconfig.*.json
    options:
      parser: jsonc
