# Modified copy of https://github.com/Azure/azure-rest-api-specs/blob/main/.github/workflows/github-test.yaml

name: GitHub Actions - Test

on:
  push:
    branches:
      - main
    paths:
      - .github/**
  pull_request:
    paths:
      - .github/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, windows]

    runs-on: ${{ fromJSON('{"ubuntu":"ubuntu-24.04", "windows":"windows-2022"}')[matrix.os] }}

    defaults:
      run:
        working-directory: ./.github

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          sparse-checkout: |
            .github

      # Content copied from https://raw.githubusercontent.com/rhysd/actionlint/2ab3a12c7848f6c15faca9a92612ef4261d0e370/.github/actionlint-matcher.json
      - if: ${{ matrix.os == 'ubuntu'}}
        name: Add ActionLint Problem Matcher
        run: echo "::add-matcher::.github/matchers/actionlint.json"

      - if: ${{ matrix.os == 'ubuntu'}}
        name: Lint workflows
        uses: docker://rhysd/actionlint:1.7.10
        with:
          args: -color -verbose

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          # actions/github-script@v8 uses Node 24
          node-version: 24.x

      - name: Install runtime deps
        run: npm ci --omit dev

      - name: Verify all modules are importable
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const { join } = await import("path");
            const { pathToFileURL } = await import("url");
            const fullPath = join(process.env.GITHUB_WORKSPACE, ".github", "workflows", "src", "github-test.js");
            const { default: importAllModules } = await import(pathToFileURL(fullPath).href);
            await importAllModules({ core });

      - name: Install dev deps
        run: npm ci

      - run: npm run lint

      - run: npm run format:check:ci

      - run: npm run test:ci

      - name: Archive code coverage results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: code-coverage-report-${{ matrix.os }}
          path: ./.github/coverage
          if-no-files-found: ignore
