name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, windows]
        node-version: [20, 24]
        exclude:
          - os: ubuntu
            node-version: 24
          - os: windows
            node-version: 20

    runs-on: ${{ fromJSON('{"ubuntu":"ubuntu-24.04", "windows":"windows-2022"}')[matrix.os] }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Use Node ${{ matrix.node-version }}.x
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node-version }}.x

      - name: rush install
        run: node common/scripts/install-run-rush.js install

      - name: rush build
        run: node common/scripts/install-run-rush.js build --verbose

      - name: rush lint
        run: node common/scripts/install-run-rush.js lint

      - name: rush test
        run: node common/scripts/install-run-rush.js test

      - name: rush regen-ruleindex
        run: node common/scripts/install-run-rush.js regen-ruleindex

      - name: rush pack
        if: contains(matrix.os, 'ubuntu')
        run: node common/scripts/install-run-rush.js pack

      - name: Upload npm packages
        if: contains(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: packages
          path: |
            packages/**/*.tgz
            !packages/**/node_modules/**
          if-no-files-found: error
