parameters:
- name: 'NodeVersion'
  default: '22.x'
  type: string

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '${{ parameters.NodeVersion }}'
    displayName: 'Install Node.js ${{ parameters.NodeVersion }}'

  - template: /eng/common/pipelines/templates/steps/create-authenticated-npmrc.yml
    parameters:
      npmrcPath: $(Agent.TempDirectory)/aoav.npmrc

  - pwsh: |
      $rushJson = Get-Content -Raw "$(Build.SourcesDirectory)/rush.json" | ConvertFrom-Json
      npm install -g "pnpm@$($rushJson.pnpmVersion)"
    displayName: 'Install pnpm'
    env:
      NPM_CONFIG_USERCONFIG: '$(Agent.TempDirectory)/aoav.npmrc'

  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'rush install'
    env:
      NPM_CONFIG_USERCONFIG: '$(Agent.TempDirectory)/aoav.npmrc'

  - script: 'node common/scripts/install-run-rush.js rebuild --verbose'
    displayName: 'rush build'