parameters:
  - name: Version
    type: string
    default: 'beta'
    values:
      - 'beta'
      - 'latest'

stages:
  - stage: Release
    displayName: Release ${{ parameters.Version }}
    dependsOn: Build

    jobs:
      - deployment: Publish
        environment: 'package-publish'
        pool:
          name: azsdk-pool
          image: ubuntu-24.04
          os: linux

        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
                submodules: false

              - download: current
                artifact: drop
                timeoutInMinutes: 5

              - pwsh: |
                  Write-Host "Will deploy with tag of ${{ parameters.Version }}"
                  Get-ChildItem "$(Pipeline.Workspace)/drop" -Recurse -Force `
                    | Where-Object { $_.Name -like "*.tgz" } `
                    | Copy-Item -Destination "$(Build.ArtifactStagingDirectory)"

                  Get-ChildItem "$(Build.ArtifactStagingDirectory)" -Recurse -Force | % { Write-Host $_.FullName }
                displayName: Move artifact to $(Build.ArtifactStagingDirectory)

              - task: EsrpRelease@9
                displayName: 'Publish to ESRP'
                inputs:
                  ConnectedServiceName: 'Azure SDK PME Managed Identity'
                  ClientId: '5f81938c-2544-4f1f-9251-dd9de5b8a81b'
                  DomainTenantId: '975f013f-7f24-47e8-a7d3-abc4752bf346'
                  UseManagedIdentity: true
                  KeyVaultName: 'kv-azuresdk-codesign'
                  SignCertName: 'azure-sdk-esrp-release-certificate'
                  Intent: 'PackageDistribution'
                  ContentType: 'npm'
                  FolderLocation: $(Build.ArtifactStagingDirectory)
                  Owners: ${{ coalesce(variables['Build.RequestedForEmail'], 'azuresdk@microsoft.com') }}
                  Approvers: 'azuresdk@microsoft.com'
                  ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
                  MainPublisher: 'ESRPRELPACMANTEST'
                  productstate: ${{ parameters.Version }}