parameters:
  - name: Version
    type: string
    default: 'beta'
    values:
      - 'beta'
      - 'latest'

stages:
  - stage: Release
    displayName: Release ${{ parameters.Version }}
    dependsOn: Build

    jobs:
      - deployment: Publish
        environment: 'package-publish'
        pool:
          name: azsdk-pool
          image: ubuntu-24.04
          os: linux
          
        variables:
        - name: ArtifactPath
          value: $(Pipeline.Workspace)/drop

        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            artifactName: drop
            itemPattern: '**/*.tgz'
            targetPath: $(ArtifactPath)
            
        strategy:
          runOnce:
            deploy:
              steps:
              - pwsh: |
                  Write-Host "Will deploy with tag of ${{ parameters.Version }}"
                  Get-ChildItem "$(ArtifactPath)" *.tgz -Recurse | % { Write-Host $_.FullName }
                displayName: Packages to be published

              - task: EsrpRelease@9
                displayName: 'Publish to ESRP'
                inputs:
                  ConnectedServiceName: 'Azure SDK PME Managed Identity'
                  ClientId: '5f81938c-2544-4f1f-9251-dd9de5b8a81b'
                  DomainTenantId: '975f013f-7f24-47e8-a7d3-abc4752bf346'
                  UseManagedIdentity: true
                  KeyVaultName: 'kv-azuresdk-codesign'
                  SignCertName: 'azure-sdk-esrp-release-certificate'
                  Intent: 'PackageDistribution'
                  ContentType: 'npm'
                  FolderLocation: $(ArtifactPath)
                  Owners: ${{ coalesce(variables['Build.RequestedForEmail'], 'azuresdk@microsoft.com') }}
                  Approvers: 'azuresdk@microsoft.com'
                  ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
                  MainPublisher: 'ESRPRELPACMANTEST'
                  productstate: ${{ parameters.Version }}
